In [4]:
import numpy as np


In [5]:
np. __version__


'1.26.4'

In [6]:
import sys
sys.version

'3.12.7 | packaged by Anaconda, Inc. | (main, Oct  4 2024, 13:17:27) [MSC v.1929 64 bit (AMD64)]'

In [53]:
#### CREATING A LIST HERE 

my_List=[1,2,3,4,5,6]
#my_List
print(type(my_List))


<class 'list'>


In [8]:
type(my_List)

list

In [10]:
## Converting LIST TO ARRAY 


arr = np.array(my_List)
arr

array([1, 2, 3, 4, 5, 6])

In [11]:
type(arr)

numpy.ndarray

In [13]:
print(type(arr))
print(type(my_List))

<class 'numpy.ndarray'>
<class 'list'>


In [18]:
np.arange()


TypeError: arange() requires stop to be specified.

In [17]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [20]:
np.arange(10,50,5)

array([10, 15, 20, 25, 30, 35, 40, 45])

In [21]:
np.arange(10,50,3)

array([10, 13, 16, 19, 22, 25, 28, 31, 34, 37, 40, 43, 46, 49])

In [23]:
np.arange(10,20,30, 3) # why means u do shift , Tab it will show explanation

TypeError: Cannot interpret '3' as a data type

In [ ]:
#### Arange() function is only applied to numpy , not List() only in numpy

In [ ]:
## if you do 

In [25]:
np.arange(8,20)

array([ 8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [ ]:
np.arange(20,8)

In [24]:
### but when you do np.arange(20,8)

array([], dtype=int32)

In [ ]:
## first argument should be always less then second argument then it will print array metrics

## second argument is greater then first , u will get error or some other output

In [54]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [ ]:
## so in np.arange() always 1 arg  >>   2 arg

In [ ]:
## so everytime we are writing np.arange()  WE CAN REFER TO OBEJCT LIKE BELOW

In [28]:
n= np.arange(2,8)
np.

array([2, 3, 4, 5, 6, 7])

In [29]:
np.zeros(3) ### parameter tuning means we get out put as float

array([0., 0., 0.])

In [32]:
np.zeros(3,dtype=int) ##hHyper parameter tuning , in LLM its called FineTune  that means here we are changing system 
                      ## we are changing system parameter

array([0, 0, 0])

In [ ]:
### when u shift Tab , the system gives you its a float type , but when



In [33]:
z=np.zeros(5)
z

array([0., 0., 0., 0., 0.])

In [42]:
z=np.zeros((5,9))
z

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [45]:
z=np.zeros((5,9) , dtype=int)
z

array([[0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [46]:
len(z)

5

In [47]:
np.ones(3)

array([1., 1., 1.])

In [48]:
np.ones(3 , dtype=int)

array([1, 1, 1])

In [49]:
np.ones((10,10) , dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [ ]:
### the above one is N dimension array 

In [ ]:
## we cannot use any other digit other then Zeros and Ones , as this would be like pixel format

In [ ]:
### if you want we can check with by doing np.tab  (you can zeros and ones)

In [50]:
## lets try 

np.three(4,5)

AttributeError: module 'numpy' has no attribute 'three'

In [55]:
np.arange(10,20,2)

array([10, 12, 14, 16, 18])

In [56]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [57]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
np.ones(3)

array([1., 1., 1.])

In [59]:
np.ones(6,dtype=int)

array([1, 1, 1, 1, 1, 1])

In [61]:
###np.ones(renu,dtype=string)

NameError: name 'renu' is not defined

In [62]:
 rand(3,2)

NameError: name 'rand' is not defined

In [63]:
np.random.rand(4)

array([0.62561929, 0.94647721, 0.94060678, 0.60362107])

In [66]:
np.random.rand(4,dtype=int)

TypeError: rand() got an unexpected keyword argument 'dtype'

In [67]:
np.random.rand(4,3)

array([[0.86469974, 0.05721204, 0.91079722],
       [0.20055839, 0.340491  , 0.23747349],
       [0.84855648, 0.82883505, 0.73162199],
       [0.67898928, 0.05366355, 0.13577264]])

In [71]:
np.random.randint(3)

1

In [77]:
np.random.randint(3,20,5)

array([12, 14, 18, 18,  3])

In [81]:
np.random.randint(10,300,(10,50))

array([[143, 252, 177,  74, 128,  79, 192, 205,  16, 145, 172, 217, 271,
        182, 218,  68, 113, 292,  23, 146, 162, 279, 232,  53, 180,  14,
        266, 117, 289, 243,  78, 263,  19, 216,  50, 180, 253, 143, 183,
        191, 164,  92, 122,  60, 212, 204, 152,  80, 188, 122],
       [ 59, 226,  16, 176,  32, 220, 179, 295, 292,  29, 151, 173,  65,
        111, 185, 146,  90, 200,  58, 138, 215,  99,  97, 136, 151, 125,
        147, 174, 254, 110, 135, 238, 199, 223, 254, 119, 119, 282, 116,
        271, 135, 175,  57,  19,  28, 127, 232, 115, 157,  37],
       [ 26, 298, 121, 123,  54,  33, 286, 104, 215,  54,  31, 267, 191,
        162, 295, 146, 237, 142,  81, 282, 141, 144, 293, 297,  17, 231,
        105, 102, 131, 166, 189, 243,  82, 120, 161, 144,  20, 207, 131,
         22, 147,  27, 223,  56, 261, 239,  38, 234,  98, 220],
       [157, 251,  43, 231, 166, 131, 195, 142,  59, 119,  65, 243, 258,
        224, 283, 219,  86, 166,  90, 111, 264, 170, 135, 111, 140, 285,
     

In [82]:
arr

array([1, 2, 3, 4, 5, 6])

In [83]:
arr.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [84]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [85]:
arr.reshape(6,1)


array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [86]:
arr=(1,2,3,4,5,6,7,8,9)

In [87]:
arr

(1, 2, 3, 4, 5, 6, 7, 8, 9)

In [88]:
arr=[1,2,3,4,5,6,7,8,9]

In [89]:
arr

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [90]:
np.reshape(3,3)

ValueError: cannot reshape array of size 1 into shape (3,)

In [91]:
arr1 = np.array(arr)

In [92]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
arr1.reshape(3,3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [94]:
b=np.random.randomint(4,10,(2,3))

AttributeError: module 'numpy.random' has no attribute 'randomint'

In [95]:
b = np.random.randomint(10,20,(5,4))

AttributeError: module 'numpy.random' has no attribute 'randomint'

In [96]:
b=np.random.randint(10,20,(5,4))

In [97]:
b

array([[16, 12, 11, 18],
       [16, 13, 11, 13],
       [11, 19, 12, 12],
       [16, 18, 14, 14],
       [14, 13, 10, 14]])

In [98]:
b[4,4]

IndexError: index 4 is out of bounds for axis 1 with size 4

In [99]:
b[4:4]


array([], shape=(0, 4), dtype=int32)

In [100]:
b[2:3]

array([[11, 19, 12, 12]])

In [101]:
b[2:2]

array([], shape=(0, 4), dtype=int32)

In [102]:
b[1:2]

array([[16, 13, 11, 13]])

In [103]:
b[1:]

array([[16, 13, 11, 13],
       [11, 19, 12, 12],
       [16, 18, 14, 14],
       [14, 13, 10, 14]])

In [104]:
b[1:4]

array([[16, 13, 11, 13],
       [11, 19, 12, 12],
       [16, 18, 14, 14]])

In [8]:
b


NameError: name 'b' is not defined

In [106]:
b[2:4]

array([[11, 19, 12, 12],
       [16, 18, 14, 14]])

In [ ]:
#### Difference between slicing and Come --> Slicing will give entire Row 
## when you put come , it will vgive specific number like below


In [ ]:
### same example we wil take now 

In [4]:
a=np.random.randint(10,20,(5,4))

NameError: name 'np' is not defined

In [6]:
print(b)

NameError: name 'b' is not defined

In [9]:
a=np.random.randint(10,20,(5,4))

NameError: name 'np' is not defined

In [13]:
import numpy as np

In [14]:
a=np.random.randint(10,20,(5,4))

In [15]:
a

array([[13, 15, 16, 15],
       [19, 11, 18, 10],
       [13, 19, 19, 15],
       [12, 15, 10, 11],
       [13, 10, 19, 10]])

In [16]:
a[1,2]

18

In [ ]:
### slicing gives you complete row , and coma gives you specific value

In [17]:
a[1,-1]

10

In [18]:
a[1,-2]

18